### ISSUE TITLE
Json object as string  

### ISSUE THREAD

**Issue by LucasLuann** [hudsonventura/LogCenter#4]
When saving a json, it needs to be saved as an object and not as a string
 
![image](https://github.com/user-attachments/assets/b1218b55-2d98-438a-99e9-953e7fb49038)

**Comment by hudsonventura** [comment]
Commit: 20c68755ea99957299e0a73b9ebec8a6fcaa8706
Parents: ff691b9e09e2cb9e90cca56f6cb1d5070f274083
Author: Hudson Ventura <[hudsonventura@outlook.com](mailto:hudsonventura@outlook.com)>
Committer: Hudson Ventura <[hudsonventura@outlook.com](mailto:hudsonventura@outlook.com)>
Date: Fri Oct 04 2024 17:06:35 GMT-0400 (Amazon Standard Time)
 

Eliminating issue #4 Json object as string
